export const FIREBASE_URL = 'https://contact-manager-62af7-default-rtdb.firebaseio.com';

export const ActionTypes = {
    ADD_CONTACT: "ADD_CONTACT",
    ADD_FAVOURITE: "ADD_FAVOURITE",
    REMOVE_CONTACT: "REMOVE_CONTACT",
    REMOVE_FAVOURITE: "REMOVE_FAVOURITE",
    GET_CONTACTS: "GET_CONTACTS",
    GET_FAVOURITES: "GET_FAVOURITES",
    GET_PEOPLE: "GET_PEOPLE",
    PEOPLE_ERROR: "PEOPLE_ERROR",
}